package Lib;


/**
* Lib/LibraryPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Library.idl
* Thursday, 3 April, 2014 8:14:25 PM IST
*/

public abstract class LibraryPOA extends org.omg.PortableServer.Servant
 implements Lib.LibraryOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("get_book", new java.lang.Integer (0));
    _methods.put ("addBook", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Lib/Library/get_book
       {
         String id = in.read_string ();
         String $result = null;
         $result = this.get_book (id);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // Lib/Library/addBook
       {
         String id = in.read_string ();
         String date = in.read_string ();
         String book = in.read_string ();
         this.addBook (id, date, book);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Lib/Library:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Library _this() 
  {
    return LibraryHelper.narrow(
    super._this_object());
  }

  public Library _this(org.omg.CORBA.ORB orb) 
  {
    return LibraryHelper.narrow(
    super._this_object(orb));
  }


} // class LibraryPOA
