package Lib;


/**
* Lib/Library.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Library.idl
* Thursday, 3 April, 2014 8:49:34 PM IST
*/

public interface Library extends LibraryOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Library
